IMPORT PYSHARK 
IMPORT SMTPLIB 
FROM EMAIL.MIME.TEXT IMPORT MIMETEXT 
FROM DATETIME IMPORT DATETIME 
# DEFINE THE EMAIL PARAMETERS 
SMTP_SERVER = 'SMTP.GMAIL.COM' 
SMTP_PORT = 587 
EMAIL_ADDRESS = 'system@GMAIL.COM' 
EMAIL_PASSWORD = 'use pass here'  # USE YOUR GENERATED APP PASSWORD 
TO_EMAIL = 'sender admin @GMAIL.COM' 
# COLOR CODES 
COLOR_RESET = '\033[0M' 
COLOR_RED = '\033[91M' 
COLOR_GREEN = '\033[92M' 
COLOR_YELLOW = '\033[93M' 
# FUNCTION TO SEND AN EMAIL ALERT 
DEF SEND_EMAIL_ALERT(ATTACKER_IP, PACKET_COUNT): 
SUBJECT = "ALERT: POTENTIAL DDOS ATTACK DETECTED" 
DETECTION_TIME = DATETIME.NOW().STRFTIME('%Y-%M-%D %H:%M:%S') 
BODY = (F"DEAR NETWORK ADMINISTRATOR,\N\N" 
F"OUR MONITORING SYSTEM HAS DETECTED A POTENTIAL DDOS ATTACK.\N\N" 
F"DETAILS:\N" 
F"- ATTACKER IP: {ATTACKER_IP}\N" 
F"- PACKETS PER SECOND: {PACKET_COUNT}\N" 
F"- DETECTION TIME: {DETECTION_TIME}\N\N" 
F"PLEASE REVIEW THE NETWORK TRAFFIC AND TAKE NECESSARY ACTIONS TO MITIGATE THE THREAT.\N\N" 
F"BEST REGARDS,\N" 
F"NETWORK SECURITY SYSTEM") 
MSG = MIMETEXT(BODY) 
MSG['SUBJECT'] = SUBJECT 
MSG['FROM'] = EMAIL_ADDRESS 
MSG['TO'] = TO_EMAIL 
TRY: 
WITH SMTPLIB.SMTP(SMTP_SERVER, SMTP_PORT) AS SERVER: 
SERVER.STARTTLS() 
SERVER.LOGIN(EMAIL_ADDRESS, EMAIL_PASSWORD) 
SERVER.SENDMAIL(EMAIL_ADDRESS, TO_EMAIL, MSG.AS_STRING()) 
PRINT(F"{COLOR_GREEN}EMAIL ALERT SENT FOR ATTACKER IP: {ATTACKER_IP}, PACKET COUNT: 
{PACKET_COUNT}{COLOR_RESET}") 
EXCEPT EXCEPTION AS E: 
PRINT(F"{COLOR_RED}FAILED TO SEND EMAIL: {E}{COLOR_RESET}") 
# DEFINE A THRESHOLD VALUE FOR PACKET COUNT 
THRESHOLD = 20 
# CREATE A LIVE CAPTURE OBJECT 
CAPTURE = PYSHARK.LIVECAPTURE(INTERFACE='ENP0S3') 
# DICTIONARY TO TRACK PACKET COUNTS PER IP 
PACKET_COUNTS = {} 
# PRINT INITIAL MESSAGE 
PRINT(F"{COLOR_YELLOW}MONITORING NETWORK TRAFFIC FOR DOS ATTACK...{COLOR_RESET}") 
# START CAPTURING PACKETS 
FOR PACKET IN CAPTURE.SNIFF_CONTINUOUSLY(): 
TRY: 
IF 'IP' IN PACKET: 
IP_SRC = PACKET.IP.SRC 
# INCREMENT PACKET COUNT FOR THE SOURCE IP 
IF IP_SRC IN PACKET_COUNTS: 
PACKET_COUNTS[IP_SRC] += 1 
ELSE: 
PACKET_COUNTS[IP_SRC] = 1 
# CHECK IF THE PACKET COUNT EXCEEDS THE THRESHOLD 
IF PACKET_COUNTS[IP_SRC] > THRESHOLD: 
MESSAGE = (F"{COLOR_RED}POTENTIAL DOS ATTACK DETECTED FROM IP: {IP_SRC}. " 
F"PACKET COUNT: {PACKET_COUNTS[IP_SRC]}{COLOR_RESET}") 
PRINT(MESSAGE) 
SEND_EMAIL_ALERT(IP_SRC, PACKET_COUNTS[IP_SRC]) 
# CONTINUE SENDING ALERTS FOR EACH ADDITIONAL PACKET 
THRESHOLD = PACKET_COUNTS[IP_SRC] + 1  # UPDATE THRESHOLD TO ALWAYS ALERT FOR ADDITIONAL 
PACKETS 
EXCEPT ATTRIBUTEERROR: 
# SOME PACKETS MIGHT NOT HAVE AN IP LAYER, SO WE SKIP THEM 
PASS 
